# Read about `build.yaml` at https://pub.dev/packages/build_config

builders:
  about:
    import: "tools/builders.dart"
    builder_factories:
      - pubspecBuilder
    build_extensions: { "$lib$": ["pubspec.dart"] }
    auto_apply: root_package
    build_to: cache
