name: about
description: Displays an About dialog, which describes the application, can show licenses, changelog, and other information.
author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/flutter_about
version: 2.0.0-nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^3.0.0
  flutter_markdown: ^0.5.1
  url_launcher: ^6.0.0-nullsafety
  path: ^1.8.0-nullsafety
  simple_mustache: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
