name: about
description: Displays an About dialog, which describes the application, can show licenses, changelog, and other infomation.
authors:
  - David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/flutter_about
version: 1.0.3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0
  markdown: ^2.1.1
  flutter_markdown: ^0.3.0
  url_launcher: ^5.1.0
  path: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic:
  build: ^1.2.0
  build_config: ^0.4.0
  yaml: ^2.2.0
  dart_style: ^1.3.0

flutter:
